# .github/release.yml

changelog:
  categories:
    - title: 💡 New Features
      labels:
        - feature
    - title: ⚡ Improvements
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📝 Other Changes
      labels:
        - '*'
