version: '3.8'

services:
  api:
    container_name: api_c
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - default

  svelte:
    container_name: svelte_c
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - default
    ports:
      - 80:80
    depends_on:
      - api

networks:
  default:
