[build]
  command = "npm run build"
  publish = "build"
  # This ignores the workflow if changes are only related to documentation
  ignore = "bash -c 'if git log -1 --name-only | grep -q \"^docs/\"; then exit 0; else exit 1; fi'"