spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: myadminpassword
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
  h2:
    console.enabled: true