spring:
  # Request size
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # Database
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: myadminpassword
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
  # Security
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/CsgoNade
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CsgoNade

server:
  port: 8081

# logging:
#   level:
#     org.springframework.security: DEBUG
#     web: DEBUG