spring:
  # Request size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Database
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: myadminpassword
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
  h2:
    console.enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    web: DEBUG