create table "public"."bug_reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text not null,
    "description" text not null,
    "user_id" bigint
);


alter table "public"."bug_reports" enable row level security;

CREATE UNIQUE INDEX bug_reports_pkey ON public.bug_reports USING btree (id);

alter table "public"."bug_reports" add constraint "bug_reports_pkey" PRIMARY KEY using index "bug_reports_pkey";

alter table "public"."bug_reports" add constraint "bug_reports_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."bug_reports" validate constraint "bug_reports_user_id_fkey";

create policy "Disable deletion"
on "public"."bug_reports"
as permissive
for delete
to public
using (false);


create policy "Disable read access"
on "public"."bug_reports"
as permissive
for select
to public
using (false);


create policy "Disable update"
on "public"."bug_reports"
as permissive
for update
to public
using (false)
with check (false);


create policy "Enable insert for authenticated users only"
on "public"."bug_reports"
as permissive
for insert
to authenticated
with check (true);



